### ISSUE TITLE
`#getValueId` is not implemented for the DSpace::CLI::Metadatum Class

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-cli#120]
When attempting to update individual Metadatum objects, there are failures tracing to the following:

```ruby
dspace-cli/dspace/cli/metadatum.rb:313:in `update'
dspace-cli/dspace/cli/metadatum.rb:303:in `persisted?'
dspace-cli/dspace/cli/metadatum.rb:286:in `database_row'
dspace-cli/dspace/cli/metadatum.rb:29:in `id'
NoMethodError (undefined method `getValueId' for #<Java::OrgDspaceContent::Metadatum:0x69a2b3b6>)
```

**Comment by jrgriffiniii** [comment]
This is indeed an expected error, as this method is not implemented on the underlying DSpace Class:

https://github.com/DSpace/DSpace/blob/dspace-5.5/dspace-api/src/main/java/org/dspace/content/Metadatum.java#L20

**Comment by jrgriffiniii** [comment]
This is also going to block all updates for Item metadata, as the following would, then, raise the same error for `DSpace::CLI::MetadataArray` (please see https://github.com/pulibrary/dspace-cli/blob/main/dspace/cli/metadata_array.rb#L79).

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/dspace-cli/tree/issues-120-jrgriffiniii-metadatum-update advances this to the point where metadata records are being updated when tested on the staging environment.
