### ISSUE TITLE
Outline the process for working with the JRuby interpreter on the servers

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-cli#40]
From the home directory on updatespace, as the `dspace` user, one invokes the following:

```
ruby/cli/idspace
```

This becomes problematic on updatespace given the following:
```
irb(main):003:0> require 'dspace'
=> true
irb(main):004:0> DSpace.load
Using /dspace
Loading jars
LoadError: cannot load such file -- /dspace/lib/JUnitParams-1.0.2.jar
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /u/dspace/ruby/dspace-jruby/lib/dspace/dspace.rb:272:in `block in init'
	from /u/dspace/ruby/dspace-jruby/lib/dspace/dspace.rb:271:in `each'
	from /u/dspace/ruby/dspace-jruby/lib/dspace/dspace.rb:271:in `init'
	from /u/dspace/ruby/dspace-jruby/lib/dspace/dspace.rb:259:in `context'
	from /u/dspace/ruby/dspace-jruby/lib/dspace/dspace.rb:62:in `context'
	from /u/dspace/ruby/dspace-jruby/lib/dspace/dspace.rb:36:in `load'
	from (irb):4
	from /usr/bin/irb:12:in `<main>'
```

**Comment by jrgriffiniii** [comment]
For certain server environments (e. g. oar.princton.edu) `irb` does not reference the Ruby system interpreter, but that of JRuby:

```
dspace@oar-prod-repo: master item-release> which irb
/u/dspace/software/jruby/bin/irb
```

This, then, it used to initiate the REPL interpreter for JRuby:
```
dspace@oar-prod-repo: master item-release> cat ~dspace/ruby/cli/idspace
#!/bin/tcsh
irb -I ../dspace-jruby/lib $*
```

The `-I` argument dynamically loads libraries/Gems into the interpreter environment. `$*` then directs all arguments passed to the `tcsh` script directly into the interpreter. For example:

```
> source ~dspace/ruby/cli/idspace foo bar
```

will actually just invoke:

```
irb -I ../dspace-jruby/lib foo bar
```

**Comment by jrgriffiniii** [comment]
`~dspace/ruby/dspace-jruby/lib/` (the directory passed to `-I`) contains all Classes and Modules for the `dspace-jruby` Gem (it essentially includes the entire Gem)
