### ISSUE TITLE
JRuby cannot be used to run DSpace CLI tasks on the DataSpace QA environment

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/dspace-cli#82]
This was discovered when trying to advance https://github.com/pulibrary/dspace-cli/issues/40

```
irb(main):003:0> require 'dspace'
=> true
irb(main):004:0> DSpace.load
Using /dspace
Loading jars
LoadError: cannot load such file -- /dspace/lib/JUnitParams-1.0.2.jar
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /u/dspace/ruby/dspace-jruby/lib/dspace/dspace.rb:272:in `block in init'
	from /u/dspace/ruby/dspace-jruby/lib/dspace/dspace.rb:271:in `each'
	from /u/dspace/ruby/dspace-jruby/lib/dspace/dspace.rb:271:in `init'
	from /u/dspace/ruby/dspace-jruby/lib/dspace/dspace.rb:259:in `context'
	from /u/dspace/ruby/dspace-jruby/lib/dspace/dspace.rb:62:in `context'
	from /u/dspace/ruby/dspace-jruby/lib/dspace/dspace.rb:36:in `load'
	from (irb):4
	from /usr/bin/irb:12:in `<main>'
```

**Comment by jrgriffiniii** [comment]
This seems to have been related to some issues with `bundler`. The following can be used to access the JRuby command-line REPL:

```
$ pwd
/usr/local/DR/home/dspace/ruby/dspace-jruby
$ set dspacedir = ~/ruby/dspace-jruby
$ jruby -I $dspacedir/lib ruby/dspace-jruby/bin/idspace
irb(main):001:0> DSpace.load
Using /dspace
Loading jars
Loading /dspace/config/dspace.cfg
INFO: Loading provided config file: /dspace/config/dspace.cfg
log4j:WARN No appenders could be found for logger (org.dspace.core.ConfigurationManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
INFO: Using dspace provided log configuration (log.init.config)
INFO: Loading: /dspace/config/log4j.properties
log4j:ERROR Could not find value for key log4j.appender.A6.layout
Starting new DSpaceKernel
DB jdbc:oracle:thin:@x110-scan.princeton.edu:1521/dspqual.world, UserName=DSPACE, Oracle JDBC driver
=> true
```

**Comment by jrgriffiniii** [comment]
In order to gain admin. privileges, I needed to create a separate, dedicated admin. account using the Java command-line interface (please see `create-administrator` on https://wiki.lyrasis.org/display/DSDOC5x/Command+Line+Operations). I have granted `jrg5` and `kmcelwee` administrative privileges with this using JRuby:

```
irb(main):003:0> DSpace.login('dspace-admin2@princeton.edu')
=> nil
irb(main):004:0> person = DEPerson.find('jrg5@princeton.edu')
=> #<Java::OrgDspaceEperson::EPerson:0x70e00c84>
irb(main):005:0> person.getNetid
=> nil
irb(main):006:0> person.setNetid('jrg5')
=> nil
irb(main):007:0> person.update
=> nil
irb(main):008:0> DSpace.commit
=> nil
irb(main):009:0> person = DEPerson.find('kmcelwee@princeton.edu')
=> #<Java::OrgDspaceEperson::EPerson:0x156a147a>
irb(main):010:0> person.getNetid
=> "kmcelwee"
irb(main):011:0> java_import org.dspace.eperson.Group
=> [Java::OrgDspaceEperson::Group]
irb(main):012:0> admins = Java::OrgDspaceEperson::Group.find(DSpace.context, 1)
=> #<Java::OrgDspaceEperson::Group:0x27225261>
irb(main):013:0> admins.addMember(person)
=> nil
irb(main):014:0> admins.isMember(person)
=> true
irb(main):015:0> admins.update
=> nil
irb(main):016:0> DSpace.commit
=> nil
irb(main):017:0>
```

**Comment by jrgriffiniii** [comment]
One should now able able to authenticate over the CAS and access the user dashboard:

![image](https://user-images.githubusercontent.com/1443986/84833933-5290d980-affe-11ea-84b0-4024be87c774.png)
